version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: sdui-redis
    ports:
      - "6379:6379"
    networks:
      - sdui-network

  app:
    build:
      context: ./Ai-Diary-server
      dockerfile: Dockerfile
    container_name: sdui-backend
    ports:
      - "8080:8080"
    depends_on:
      - redis
    environment:
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
    networks:
      - sdui-network

networks:
  sdui-network:
    driver: bridge