spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  data:
    redis:
      host: sdui-redis
      port: 6379
  mail:
    password: ${MAIL_PASSWORD}

jwt:
  secret-key: ${JWT_SECRET_KEY}

app:
  url:
    web: ${WEB_URL:http://sdui-delta.vercel.app}
    mobile: ${MOBILE_URL:http://sdui-delta.vercel.app://}

kakao:
  redirect-uri: http://43.201.237.68:8080/api/kakao/callback