name: Deploy to AWS with Docker

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        working-directory: ./SDUI-server

      - name: Build with Gradle
        run: ./gradlew clean build -x test
        working-directory: ./SDUI-server

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Docker build and push
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/sdui-app:latest ./SDUI-server
          docker push ${{ secrets.DOCKER_USERNAME }}/sdui-app:latest

      - name: Deploy to AWS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USERNAME }}
          key: ${{ secrets.AWS_KEY }}
          script: |
            docker network inspect sdui-network >/dev/null 2>&1 || docker network create sdui-network
            docker pull ${{ secrets.DOCKER_USERNAME }}/sdui-app:latest
            docker stop sdui-backend || true
            docker rm sdui-backend || true
            docker run -d --name sdui-backend \
              -p 8080:8080 \
              --network sdui-network \
              -e SPRING_PROFILES_ACTIVE=prod \
              -e SPRING_DATASOURCE_URL=jdbc:postgresql://sdui-db:5432/SDUI_TD \
              -e SPRING_DATASOURCE_USERNAME=${{ secrets.DB_USERNAME }} \
              -e SPRING_DATASOURCE_PASSWORD=${{ secrets.DB_PASSWORD }} \
              -e SPRING_DATA_REDIS_HOST=sdui-redis \
              -e SPRING_MAIL_PASSWORD=${{ secrets.MAIL_PASSWORD }} \
              -e JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }} \
              ${{ secrets.DOCKER_USERNAME }}/sdui-app:latest